### ISSUE TITLE
新版考试

### ISSUE THREAD

**Issue by C315703603** [ginnnnnn666/GinsMooc#3]
请问，这个不支持新版考试吗？
![FD9C4E{5D 0)))($EW78UL7](https://github.com/ginnnnnn666/GinsMooc/assets/103497700/19262008-e233-4569-8091-1c56b0b321e8)

**Comment by ginnnnnn666** [comment]
给下课程信息，我看一下

**Comment by C315703603** [comment]
> 给下课程信息，我看一下

https://www.icourse163.org/learn/HNCC-1207006805?tid=1470108446#/learn/announce

**Comment by ginnnnnn666** [comment]
已更新插件，可以重新下载再试试看
