### ISSUE TITLE
新版考试好像还是不行

### ISSUE THREAD

**Issue by Flanwale** [ginnnnnn666/GinsMooc#6]
![image](https://github.com/ginnnnnn666/GinsMooc/assets/133889387/fa29a571-f544-4766-a2ad-5ef45632bf7b)
点获取答案没反应

**Comment by Flanwale** [comment]
https://www.icourse163.org/spoc/learn/ZJU-1468750167?tid=1470071476
这是课程信息

**Comment by ginnnnnn666** [comment]
课程密码给一下

**Comment by Flanwale** [comment]
23chunmodian

**Comment by ginnnnnn666** [comment]
spoc，加入不了，获取不了

**Comment by Flanwale** [comment]
没事
